// Datos de demostración para desarrollo
// Estos datos se usan cuando el backend no está disponible

import type { Category, Product, LandingPageData, LandingSection, User } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Electrónica",
    description: "Dispositivos electrónicos y tecnología de última generación",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Ropa y Moda",
    description: "Ropa, calzado y accesorios de moda",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Hogar y Jardín",
    description: "Artículos para el hogar y jardín",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Deportes",
    description: "Equipamiento deportivo y fitness",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  // Electrónica
  {
    id: "1",
    name: "Smartphone Pro Max",
    description: "El smartphone más avanzado con pantalla de 6.7 pulgadas, cámara de 108MP y procesador de última generación. Incluye carga rápida y resistencia al agua.",
    price: 899.99,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
    categoryId: "1",
    stock: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Laptop Ultrabook",
    description: "Laptop ligera y potente con procesador Intel i7, 16GB RAM, SSD de 512GB y pantalla Full HD de 14 pulgadas. Perfecta para trabajo y entretenimiento.",
    price: 1299.99,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800",
    categoryId: "1",
    stock: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Auriculares Inalámbricos",
    description: "Auriculares con cancelación de ruido activa, batería de 30 horas y calidad de sonido Hi-Fi. Incluyen estuche de carga.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    categoryId: "1",
    stock: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Smartwatch Fitness",
    description: "Reloj inteligente con monitor de frecuencia cardíaca, GPS integrado, resistencia al agua y batería de 7 días.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    categoryId: "1",
    stock: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Ropa y Moda
  {
    id: "5",
    name: "Chaqueta de Cuero",
    description: "Chaqueta de cuero genuino con forro interior, diseño clásico y atemporal. Disponible en varios colores.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800",
    categoryId: "2",
    stock: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Zapatillas Deportivas",
    description: "Zapatillas cómodas y resistentes con tecnología de amortiguación avanzada. Ideales para correr y caminar.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
    categoryId: "2",
    stock: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Vestido Elegante",
    description: "Vestido elegante para ocasiones especiales, hecho con materiales de alta calidad y diseño moderno.",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800",
    categoryId: "2",
    stock: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Hogar y Jardín
  {
    id: "8",
    name: "Set de Ollas Premium",
    description: "Set completo de ollas y sartenes antiadherentes de acero inoxidable. Incluye 10 piezas.",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800",
    categoryId: "3",
    stock: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Aspiradora Robot",
    description: "Aspiradora robot inteligente con mapeo de habitaciones, control por app y programación automática.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800",
    categoryId: "3",
    stock: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Mesa de Comedor",
    description: "Mesa de comedor de madera maciza con capacidad para 6 personas. Diseño moderno y elegante.",
    price: 599.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    categoryId: "3",
    stock: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Deportes
  {
    id: "11",
    name: "Bicicleta de Montaña",
    description: "Bicicleta de montaña con suspensión delantera, frenos de disco y 21 velocidades. Perfecta para terrenos difíciles.",
    price: 549.99,
    image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800",
    categoryId: "4",
    stock: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Set de Pesas Ajustables",
    description: "Set de pesas ajustables de 2.5kg a 25kg cada una. Incluye barra y discos intercambiables.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    categoryId: "4",
    stock: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockLandingData: LandingPageData = {
  companyName: "Tienda Online Demo",
  companyDescription: "Tu tienda personalizable para todo tipo de negocio. Descubre productos de calidad y servicio excepcional.",
  logo: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200",
  sections: [
    {
      id: "1",
      type: "hero",
      title: "Bienvenido a nuestra tienda",
      content: "Descubre productos de calidad con los mejores precios del mercado",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200",
      order: 1,
      visible: true,
    },
    {
      id: "2",
      type: "about",
      title: "Sobre Nosotros",
      content: "Somos una tienda comprometida con la calidad y el servicio al cliente. Ofrecemos una amplia variedad de productos cuidadosamente seleccionados para satisfacer todas tus necesidades. Nuestro equipo está dedicado a brindarte la mejor experiencia de compra posible.",
      order: 2,
      visible: true,
    },
    {
      id: "3",
      type: "features",
      title: "¿Por qué elegirnos?",
      content: "✓ Productos de calidad garantizada\n✓ Envío rápido y seguro\n✓ Atención al cliente 24/7\n✓ Precios competitivos\n✓ Devoluciones sin complicaciones",
      order: 3,
      visible: true,
    },
    {
      id: "4",
      type: "testimonials",
      title: "Lo que dicen nuestros clientes",
      content: "\"Excelente servicio y productos de calidad. Muy recomendado!\" - María G.\n\n\"La mejor experiencia de compra online que he tenido.\" - Juan P.\n\n\"Productos excelentes y entrega rápida. Volveré a comprar.\" - Ana L.",
      order: 4,
      visible: true,
    },
    {
      id: "5",
      type: "contact",
      title: "Contáctanos",
      content: "¿Tienes alguna pregunta? Estamos aquí para ayudarte.\n\nEmail: contacto@tiendaonline.com\nTeléfono: +1 (555) 123-4567\nHorario: Lunes a Viernes 9:00 AM - 6:00 PM",
      order: 5,
      visible: true,
    },
  ],
};

// Función helper para simular delay de red
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
